### PR TITLE
feat: Upgrade API to be compatible with INK3

### PR DESCRIPTION
**Pull request by leipert**
Updates the API to be compatible with INK@3

BREAKING CHANGE: Requires ink@3 now

#7

### CODE REVIEW

**Review by armand1m — APPROVED** [review]

**Comment by karaggeorge** [comment]
Hey, thanks for the PR. I don't have the time to actively work on this at the moment. If someone can pull down and verify this works with Ink 3, I can merge and release a new version tomorrow

**Comment by passion4code** [comment]
Can confirm. Just pulled it down via `npm install git+https://github.com/leipert/ink-multi-select.git#leipert-ink-v3` to use as a replacement and the nifty module now works as expected. 

Edit - the only issue is the warning for the key prop in the list

**Comment by karaggeorge** [comment]
Ok, I'll merge and release this, and when I have some free time I'll try to fix that warning

**Comment by karaggeorge** [comment]
Thank you @leipert and everyone who helped

**Comment by karaggeorge** [comment]
Released as `v2.0.0`

**Pull request merged**
